### ISSUE TITLE
Address and Street structs are not namespaced

### ISSUE THREAD

**Issue by baldwindavid** [smashedtoatoms/address_us#15]
Thanks for the work on this library. Any reason not to namespace the `Address` and `Street` structs under `AddressUS`?

**Comment by baldwindavid** [comment]
I see that this was first released almost 10 years ago so that is probably the reason for the module organization. No problem, I'll fork and probably open a PR for consideration if this is still maintained. Thanks.

**Comment by smashedtoatoms** [comment]
I'll absolutely accept updates! This library is still in use and maintained, despite the infrequent changes. This was one of my first Elixir projects, so it doesn't keep up with modern standards. I've avoided changing the interface since there are people that use it. That said, we can increment the version accordingly if the interfaces change.
